### ISSUE TITLE
Ship with Fiji

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-aws-s3#2]
@igorpisarev @axtimwalde 
I saw that this is currently not shipped as part of your n5 update site: https://sites.imagej.net/N5/jars/

1. Could you add it you your update site? 
1. If you add it, I guess one also has to ship this dependency? 
```
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-s3</artifactId>
	<version>1.11.534</version>
</dependency>
```

cc @constantinpape

**Comment by tischi** [comment]
...above dependency comes in fact with a bunch of other dependencies, including

<img width="218" alt="image" src="https://user-images.githubusercontent.com/2157566/74149606-71263480-4c08-11ea-905e-bbf4d9c64a6d.png">

...and several more.

**Comment by igorpisarev** [comment]
@tischi Yes, these dependencies would need to be shipped as well, and `n5-aws-s3` would need to be included into the `pom-scijava` configuration, possibly resolving dependency clashes. We haven't done this yet because of these non-trivial dependencies, but it would be definitely nice to add it to the N5 update site!

**Comment by tischi** [comment]
OK! For now I am shipping everything with my update site: https://sites.imagej.net/EMBL-CBA/jars/
Not ideal and I will change it once we have a more official solution.

**Comment by axtimwalde** [comment]
@tischi would you mind filing a pull request to pom-scijava?

**Comment by tischi** [comment]
I feel honoured but also overestimated regarding my knowledge 😃. I think you guys have much much more of a clue which dependencies are really needed for this to work properly. So frankly, I would prefer if e.g., @igorpisarev is doing it, just to avoid me screwing things up...

**Comment by axtimwalde** [comment]
Shipping with Fiji for a while :).
