### ISSUE TITLE
Improve testing whether anonymous credentials are working

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-aws-s3#32]
Hi @bogovicj,

Listing the bucket here to find out whether the credentials work could be slow: https://github.com/saalfeldlab/n5-aws-s3/blob/52ad9c59b3a22731c4250f78edc2d8f8b360b329/src/main/java/org/janelia/saalfeldlab/n5/s3/AmazonS3Utils.java#L185-L194

chatGPT suggests this as an alternative:

```
    boolean hasAccess = false;
    try {
        String location = s3.getBucketLocation(bucketName);
        hasAccess = true; // If we get here, we have some level of access
    } catch (AmazonS3Exception e) {
        // Handle lack of permissions or other errors
    }
```

Do you think that could make sense and be faster?

**Comment by bogovicj** [comment]
Looks like that likely won't behave as needed, since the javadoc for [`getBucketLocation`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#getBucketLocation-java.lang.String-) says

> To use this implementation of the operation, you must be the bucket owner.

**Comment by axtimwalde** [comment]
Can we please all not ask others to look at untested ChatGPT-generated code?  We can all use ChatGPT ourselves and the real work is to find out what's real and what's not.  Let's show some respect for the limited life-time of our friends and colleagues :).

**Comment by tischi** [comment]
OK, sorry!
