### ISSUE TITLE
n5 dependency

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-aws-s3#4]
@igorpisarev 

Is it on purpose that `n5-aws-s3` does not depend on the latest version of `n5`?

https://github.com/saalfeldlab/n5-aws-s3/blob/dcb528b3cc224c273751bb00eae9562b85421622/pom.xml#L57

**Comment by igorpisarev** [comment]
No, it just hasn't been updated yet, but it will work just fine with the most recent version of N5.

I'm going to merge #3 soon where I added support for multiple containers in a single bucket, and that PR will also bump the N5 dependency to the most recent one.

**Comment by igorpisarev** [comment]
The new version 3.0.0 now depends on the most recent release of n5 (2.1.4).
